name: Publish Lua (obfuscated)

on:
  push:
    branches: [ master, actions, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install jq curl -y

      - name: LuaObfuscator REST API
        shell: bash
        run: |
          mkdir -p public
          
          # 1. Upload only script.lua to start an obfuscation session
          SESSION_DATA=$(curl -s -X POST https://luaobfuscator.com \
            -H "Content-type: multipart/form-data" \
            -H "apikey: test" \
            -F "script.lua=@script.lua")
          
          SESSION_ID=$(echo "$SESSION_DATA" | jq -r '.sessionId')

          # 2. Scramble and protect script.lua
          curl -s -X POST https://luaobfuscator.com \
            -H "Content-type: application/json" \
            -H "apikey: test" \
            -H "sessionId: $SESSION_ID" \
            --data '{"Minify": true}' \
            | jq -r '.code' > public/script.yaml

          # Rename it back to .lua after saving
          mv public/script.yaml public/script.lua

      - name: Create artifact
        uses: actions/upload-artifact@v4
        with:
          name: release_protected
          path: public/
